;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	evil-insert
	evil-mouse-drag-region
	evil-normal-state
	indent-for-tab-command
	))

(setq mc/cmds-to-run-once
      '(
	evil-mouse-drag-region
	evil-search-next
	))
