icons_format = "{icon}"

[theme]
theme = "srcery"
# [theme.overrides]
# idle_bg = "#123456"
# idle_fg = "#abcdef"

[icons]
icons = "awesome6"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

# # --- WiFi 模块 ---
# [[block]]
# block = "net"
# format = "$icon"
# interval = 5
# [[block.click]]
# button = "left"
# cmd = "bash ~/.config/i3/script/wifi-menu.sh" 
#
# # --- 蓝牙模块 ---
# [[block]]
# block = "custom"
# command = "echo  "  # 这里显示蓝牙图标
# interval = "once"
# [[block.click]]
# button = "left"
# cmd = "bash ~/.config/i3/script/bluetooth -theme '~/.config/i3status-rust/theme/simple-tokyonight.rasi' -timeout 5"

# --- 待办事项 ---
[[block]]
block = "taskwarrior"
interval = 10

# --- 屏幕亮度 (内置块) ---
[[block]]
block = "backlight"
format = ""

# --- 通知 ---
# [[block]]
# block = "custom"
# # dunst：paused=true 视为勿扰 -> 显示 🔕，否则显示 🔔
# command = "dunstctl is-paused 2>/dev/null | grep -qx true && echo '' || echo ''"
# # 只有收到信号或被点击时才更新
# interval = "once"
# # 对应 pkill -SIGRTMIN+8 i3status-rs
# signal = 8
# [[block.click]]
# button = "left"
# # 点击切换 dunst 勿扰
# cmd = "~/.config/i3/script/dunst-toggle.sh"

# --- 时间 ---
[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%A %p %I:%M')"

# [[block]]
# block = "custom"
# command = "echo  "  # 这是一个电源图标 (Nerd Font)
# interval = "once"
# [[block.click]]
# button = "left"
# # 替换为你关机脚本的绝对路径
# cmd = "~/.config/rofi/powermenu/type-4/powermenu.sh"
