# ========https://github.com/yshui/picom.git=======
#################################
#     核心后端配置 (稳定性优先)
#################################
# 使用 xrender 而不是 glx。
backend = "xrender";
# 垂直同步。
vsync = true;

#################################
#           特效设置
#################################
# 圆角
corner-radius = 10;
round-borders = 10;
# 透明度
active-opacity = 1.0;
inactive-opacity = 0.95;
# 如果卡顿，把 shadow 改为 false
shadow = false;
fading = true;  # 如果不需要淡入淡出效果，可以保持禁用
fade-delta = 10;  # 变化的增量，调整窗口透明度变化的速率
fade-in-step = 0.1;  # 淡入速度，每个步长的增量
fade-out-step = 0.1;  # 淡出速度，每个步长的增量
animations = false;  # 如果不需要动画效果，可以保持禁用
# 排除一些不需要圆角或阴影的窗口 (比如 i3 的 bar)
rounded-corners-exclude = [
  "class_g = 'i3bar'",
  "class_g = 'Dmenu'",
  "window_type = 'dock'",
  "window_type = 'desktop'"
];
shadow-exclude = [
  "class_g = 'i3bar'"
];

#################################
#           通用设置
#################################
# 这种检测方式比 glx 兼容性好
use-damage = true; 
# 避免日志垃圾
log-level = "warn";
